FROM briceburg/macos:build

#
# dex sed:macos image
#

COPY macos.patch /tmp/macos.patch
RUN curl http://opensource.apple.com/tarballs/text_cmds/text_cmds-88.tar.gz | tar -C /tmp -xzf - && \
  ( cd /tmp/text_cmds-88 ; patch -p1 < /tmp/macos.patch ) && \
  ( cd /tmp/text_cmds-88/sed ; gcc -lbsd compile.c main.c misc.c process.c -w -o /usr/local/bin/sed )

ENTRYPOINT ["/usr/local/bin/sed"]

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1"
