FROM alpine:3.4

RUN apk add --no-cache \
  bash \
  curl

# dockmaster
RUN dockmaster_version=0.1.3 && \
  curl -L http://get.iceburg.net/dockmaster/latest-0.1.x/dmc > /usr/local/bin/dmc && \
  chmod +x /usr/local/bin/dmc

# runtime

ENTRYPOINT ["dmc"]

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_envars="DOCKMASTER_*"
