FROM php:7-cli

#
# dex magerun:2 image
#

RUN apt-get update && apt-get install -y \
    bzip2 \
    curl \
    git \
    openssh-client \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libpng12-dev \
    libxml2-dev \
    libxslt1-dev \
  && rm -rf /var/lib/apt/lists/*

# n98-magerun2
RUN \
  N98_VERSION="1.1.16" ; \
  N98_MD5="3f53675eaa89b7c5064689388fc27efb" ; \
  curl -Lfo /usr/local/bin/n98-magerun2 \
    https://files.magerun.net/n98-magerun2-${N98_VERSION}.phar && \
  chmod +x /usr/local/bin/n98-magerun2 ; \
  [ "$(md5sum /usr/local/bin/n98-magerun2 | awk {'print $1'})" = "$N98_MD5" ] || exit 99

ENTRYPOINT ["/usr/local/bin/n98-magerun2"]
CMD ["list"]

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_home="~"
