FROM briceburg/dosemu2:dex


# see dosemu2 manpage for flags,
#  https://github.com/stsp/dosemu2/tree/devel/man
# (run container w/ --entrypoint=bash , then `man dosemu`)
ENV \
  DOSEMU_CMD="deltree" \
  DOSEMU_FLAGS="-dumb -q -E"
