FROM briceburg/node:6

ENV \
  DEXBUILD_NAME="cop" \
  DEXBUILD_REPO="https://github.com/jasmith590/COP.git" \
  DEXBUILD_REF="0.5.0" \
  DEXBUILD_DIR="{{ DEXBUILD_DIR | default('/build') }}"

#
# build context and pre-requisites
#

RUN ( \
  mkdir -p "${DEXBUILD_DIR}" &&\
true )

WORKDIR ${DEXBUILD_DIR}


#
# application installation and user stubbing
#

# if DEXBUILD_REF never changes, you may want to bust the docker-build cache...
# ARG DEXBUILD_NOCACHE

RUN ( \
  git init &&\
  git remote add dexbuild $DEXBUILD_REPO &&\
  git fetch dexbuild $DEXBUILD_REF &&\
  GIT_WORK_TREE="${DEXBUILD_DIR}" git checkout -f FETCH_HEAD &&\
  rm -rf .git && \
  npm install &&\
true )


#
# container runtime configuration
#

ENTRYPOINT ["{{ DEXBUILD_DIR | default('/build') }}/cop"]


#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_flags="--interactive --tty"
