FROM briceburg/php:magento-7-cli

#
# dex magerun:2 image
#

# n98-magerun2 [development]
ARG CACHE_BUST
RUN \
  curl -Lfo /usr/local/bin/n98-magerun2 \
    https://files.magerun.net/n98-magerun2-dev.phar && \
  chmod +x /usr/local/bin/n98-magerun2

ENTRYPOINT ["/usr/local/bin/n98-magerun2"]
CMD ["list"]

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_home="~"
