FROM briceburg/php:magento-7-cli

#
# dex magerun:2 image
#

# n98-magerun2
RUN \
  N98_VERSION="1.2.2" ; \
  N98_MD5="430bb28ca953b6d40df4f2a3bd615424" ; \
  curl -Lfo /usr/local/bin/n98-magerun2 \
    https://files.magerun.net/n98-magerun2-${N98_VERSION}.phar && \
  chmod +x /usr/local/bin/n98-magerun2 ; \
  [ "$(md5sum /usr/local/bin/n98-magerun2 | awk {'print $1'})" = "$N98_MD5" ] || exit 99

ENTRYPOINT ["/usr/local/bin/n98-magerun2"]
CMD ["list"]

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_home="~"
