FROM briceburg/node:6

#
# dex yarn:6-alpine image
#

RUN npm install -g --progress=false yarn

ENTRYPOINT ["/usr/bin/yarn"]

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.api="v1" \
  org.dockerland.dex.docker_home="~"
